### PR TITLE
registry:delete command

### LINKED ISSUE #19: `registry:delete` command to delete an event type
The opposite of `new`, it will delete the event type from the registry. If an event of this type has been appended to the ledger, the command will fail.

### PR DESCRIPTION
**Pull request by evert**
I just noticed that tests are passing, but they should not be passing... so I think the other tests are also broken.

Fixes #19

### CODE REVIEW

File: src/commands/registry/delete.ts [hunk 1]
```diff
@@ -0,0 +1,77 @@
+import {Flags} from '@oclif/core'
+import {TokenAwareCommand} from '../../lib/token-command'
+import {initClient} from '../../lib/client'
+import {Resource} from 'ketting';
+
+export default class Delete extends TokenAwareCommand {
+  static description = 'Deletes an event type from the registry. This only works if no events of this type have been created.'
+
+  static examples = [
+    `$ evently registry:new -n article -e add-comment
```
Comment (mattbishop) [inline src/commands/registry/delete.ts:10]: should be `registry:delete`

File: src/commands/registry/delete.ts [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+ * Loops through a Ketting links with the level3 list-entry link and finds
+ * the first resource that has the specified name property.
+ *
+ * If the resource was not found, this will throw an error.
+ */
+async function findEntryByName(parent: Resource, name: string): Promise<Resource> {
+
+  const entries = await parent
+    .followAll('https://level3.rest/patterns/list#list-entry')
+    .preferTransclude()
```
Comment (mattbishop) [inline src/commands/registry/delete.ts:67]: This fetches the bodies and looks in the data, clearly. I have to do something similar in the acceptance tests, but I'm using the deprecated `links()` call because I don't need to fetch the bodies. The link itself has a `name` field that works:

```typescript
    const entryLinks = await this.resource.links("https://level3.rest/patterns/list#list-entry")
    const entry = entryLinks.find((l) => l.name === name)
```

Comment (mattbishop) [reply src/commands/registry/delete.ts:67]: We should talk about `Prefer: tranclude="rel"` sometime, as I imagine in HAL it would place the transcluded links into `_embedded`? Not sure I understand how it should work.

Comment (evert) [reply src/commands/registry/delete.ts:67]: Ah makes sense! I never think of `name`, but I was gonna bring this up as it's a lot of extra requests the way I did this! Will switch this up

File: test/commands/ledger/reset.test.ts [hunk 3]
```diff
@@ -39,20 +38,21 @@ describe('ledger:reset', () => {
...
 
-    test
-      .stdout()
-      .command(['ledger:reset', '-t', testToken])
-      .it('resets ledger fully', (ctx) => {
-        expect(ctx.stdout).to.contain('fully')
-      })
+  })
+
+  test
```
Comment (evert) [inline test/commands/ledger/reset.test.ts:43]: Earlier I commented that all tests should be in a `it()` section, but I misunderstood what `test` was doing here. The `test` function already creates the test, so I messed up all tests to not run.

So this PR became a bit fatter because I had to fix that, and then also fix all tests that weren't actually passing.

Comment (mattbishop) [reply test/commands/ledger/reset.test.ts:43]: `before()`, nice!

File: test/helpers/http.ts [hunk 4]
```diff
@@ -20,7 +20,7 @@ type RequestShape = {
 export async function expectRequest(request: Request, shape: RequestShape) {
 
   expect(request.method).to.equal(shape.method)
-  expect(new URL(request.url).pathname).to.equal(shape.path)
+  if (shape.path !== undefined) expect(new URL(request.url).pathname).to.equal(shape.path)
```
Comment (mattbishop) [inline test/helpers/http.ts:23]: Please wrap `if` then in curly braces for consistency.

Were you around for the Apple `goto fail` bug? https://www.imperialviolet.org/2014/02/22/applebug.html I am in the camp that curly braces would have helped, but unit tests definitely would have helped this case more so.

**Review by mattbishop — APPROVED** [review]

File: src/commands/registry/delete.ts [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+      await client.follow('registry'),
+      entity
+    )
+
+    const eventRes = await followByName(
+      entityRes,
+      event
+    )
+
+    await eventRes.delete()
```
Comment (mattbishop) [inline src/commands/registry/delete.ts:46]: This delete may fail if the event type has been used in an event. See acceptance test: https://github.com/evently-cloud/api-acceptance-tests/blob/3a4c73ef04a6ef37aa3f93a272f44493efda4f50/features/registry.feature#L46

File: test/helpers/http.ts (hunk 4 above)
Comment (evert) [reply test/helpers/http.ts:23]: I _only_ ever do this if it's on the same line, but happy to change this. There's probably an eslint rule for this too so ill take a look at that.

File: src/commands/registry/delete.ts (hunk 5 above)
Comment (evert) [reply src/commands/registry/delete.ts:46]: Hey I just tested this by registing an event, appending a 'fact' event and then attempt to delete the event. Did not get an error!

Comment (evert) [reply src/commands/registry/delete.ts:46]: Errors do get bubbled up nicely to the user. If you use application/problem+json they'll just see the error you wrote, but I wanted to give you a screenshot to demonstrate
