### PR TITLE
Fix for download:ledger

### LINKED ISSUE #38: ledger:download broken
> evently ledger:download -f test.ndjson -t $EVENTlY_TOKEN                                                                                                                         14:22:48
no ledger file at test.ndjson
Downloading ledger fully.
    TypeError: Invalid state: ReadableStream is locked
    Code: ERR_INVALID_STATE

Is this a fix that has to come from Ketting?

### PR DESCRIPTION
**Pull request by evert**
The main fix is that I've updated Ketting, where this bug originated. See: https://github.com/badgateway/ketting/issues/474 for details.

Fixes #38.
Closes #40

### CODE REVIEW

File: src/lib/download/http-ledger.ts [hunk 1]
```diff
@@ -22,6 +22,7 @@ export async function openHttpLedgerReadStream(context?: ValidationContext): Pro
       'Prefer':           'return=representation',
       'Accept-Encoding':  'br'
     },
+    cache: 'no-store',
```
Comment (evert) [inline src/lib/download/http-ledger.ts:25]: Bonus change that prevents Ketting from storing the ledger in cache.

Comment (mattbishop) [reply src/lib/download/http-ledger.ts:25]: Thanks Evert! I'm glad you found something to fix in Ketting, always good to make improvements in your core library. I wonder if evently is sending back the right cache-control headers in this case though? Would ketting skip storing if cache control was `no-store`? Would we need this explicit setting in the Ketting request then?

**Review by mattbishop — APPROVED** [review]

File: src/lib/download/http-ledger.ts (hunk 1 above)
Comment (evert) [reply src/lib/download/http-ledger.ts:25]: Ketting will cache basically everything indefinitely unless asked otherwise. It's a long story, but adding cache-control would at least now not make a difference
